### ISSUE TITLE
Linking issue

### ISSUE THREAD

**Issue by ajusa** [Yardanico/cosmonim#2]
Here's the error that I'm getting:
```
/usr/bin/ld.bfd: errno: TLS reference in /usr/lib64/libm-2.34.a(w_pow.o) mismatches non-TLS reference in /home/ajusa/.cache/nim/main_d/stdlib_io.nim.c.o
/usr/bin/ld.bfd: /usr/lib64/libm-2.34.a: error adding symbols: bad value
collect2: error: ld returned 1 exit status
```
Looks like something to do with libm. Is it trying to link against my libm rather than the cosmopolitan version maybe?

**Comment by ajusa** [comment]
That is the case - manually running the GCC command that fails (and removing the -lm) fixes my issue. Is it possible for a compiler flag or something else to do that?

**Comment by Yardanico** [comment]
I didn't really investigate that issue before because Cosmopolitan stopped working with Nim for me, but with the version 2.0 of Cosmopolitan it seems to work again, and I can't reproduce your issue (I specifically used code that imports `std/math` so that it adds `-lm`). Please reopen if you find a repro again, thanks!
